---
version: "2"
services:
  zoneminder:
    build: .
    container_name: zoneminder
    image: andornaut/zoneminder
    ports:
      - 8080:80
    tmpfs: /tmp/zoneminder-tmpfs
    volumes:
      - zoneminder-events:/var/lib/zoneminder/events
      - zoneminder-images:/var/lib/zoneminder/images
      - zoneminder-mysql:/var/lib/mysql

volumes:
    zoneminder-events:
    zoneminder-images:
    zoneminder-mysql:
