---
version: "2.2"
services:
  zoneminder:
    build: .
    container_name: zoneminder
    image: andornaut/zoneminder
    init: true
    ports:
      - 8080:80
    restart: on-failure
    shm_size: '512m'
    volumes:
      - zoneminder-events:/var/lib/zoneminder/events
      - zoneminder-images:/var/lib/zoneminder/images
      - zoneminder-mysql:/var/lib/mysql

volumes:
    zoneminder-events: {}
    zoneminder-images: {}
    zoneminder-mysql: {}
